<?php
class ModelExtensionProbgBlogBlog extends Model {
    public function getCategories() {
        $key=$this->key('categories');$c=$this->getCache($key);if($c!==false)return $c;$l=(int)$this->config->get('config_language_id');
        $sql="SELECT c.*,cd.title,cd.description,cd.meta_title,cd.meta_description,cd.meta_keyword,(SELECT COUNT(*) FROM `".DB_PREFIX."probg_blog_article` a INNER JOIN `".DB_PREFIX."probg_blog_article_description` ad ON(ad.article_id=a.article_id AND ad.language_id='".$l."') WHERE a.category_id=c.category_id AND a.status='1') AS article_count FROM `".DB_PREFIX."probg_blog_category` c INNER JOIN `".DB_PREFIX."probg_blog_category_description` cd ON(cd.category_id=c.category_id AND cd.language_id='".$l."') WHERE c.status='1' ORDER BY c.sort_order ASC,cd.title ASC";
        $r=$this->db->query($sql)->rows;$this->setCache($key,$r);return $r;
    }
    public function getCategory($id){$key=$this->key('category.'.(int)$id);$c=$this->getCache($key);if($c!==false)return $c;$l=(int)$this->config->get('config_language_id');$r=$this->db->query("SELECT c.*,cd.title,cd.description,cd.meta_title,cd.meta_description,cd.meta_keyword FROM `".DB_PREFIX."probg_blog_category` c INNER JOIN `".DB_PREFIX."probg_blog_category_description` cd ON(cd.category_id=c.category_id AND cd.language_id='".$l."') WHERE c.category_id='".(int)$id."' AND c.status='1'")->row;$this->setCache($key,$r);return $r;}
    public function getArticles($data=array()){
        $key=$this->key('articles.'.sha1(json_encode($data)));$c=$this->getCache($key);if($c!==false)return $c;$l=(int)$this->config->get('config_language_id');
        $sql="SELECT a.*,ad.title,ad.short_description,ad.description,ad.meta_title,ad.meta_description,ad.meta_keyword,cd.title AS category_title FROM `".DB_PREFIX."probg_blog_article` a INNER JOIN `".DB_PREFIX."probg_blog_article_description` ad ON(ad.article_id=a.article_id AND ad.language_id='".$l."') INNER JOIN `".DB_PREFIX."probg_blog_category` c ON(c.category_id=a.category_id AND c.status='1') INNER JOIN `".DB_PREFIX."probg_blog_category_description` cd ON(cd.category_id=a.category_id AND cd.language_id='".$l."') WHERE a.status='1'";
        if(!empty($data['category_id']))$sql.=" AND a.category_id='".(int)$data['category_id']."'";$sort=isset($data['sort'])?$data['sort']:$this->config->get('module_probg_blog_sort');if($sort==='sort_order')$sql.=" ORDER BY a.sort_order ASC,a.date_added DESC,a.article_id DESC";else $sql.=" ORDER BY a.date_added DESC,a.article_id DESC";$start=max(0,isset($data['start'])?(int)$data['start']:0);$limit=max(1,isset($data['limit'])?(int)$data['limit']:(int)$this->config->get('module_probg_blog_limit'));$sql.=" LIMIT ".$start.",".$limit;$r=$this->db->query($sql)->rows;$this->setCache($key,$r);return $r;
    }
    public function getTotalArticles($category_id=0){$key=$this->key('total.'.(int)$category_id);$c=$this->getCache($key);if($c!==false)return (int)$c;$l=(int)$this->config->get('config_language_id');$sql="SELECT COUNT(*) AS total FROM `".DB_PREFIX."probg_blog_article` a INNER JOIN `".DB_PREFIX."probg_blog_article_description` ad ON(ad.article_id=a.article_id AND ad.language_id='".$l."') INNER JOIN `".DB_PREFIX."probg_blog_category` c ON(c.category_id=a.category_id AND c.status='1') WHERE a.status='1'";if($category_id)$sql.=" AND a.category_id='".(int)$category_id."'";$n=(int)$this->db->query($sql)->row['total'];$this->setCache($key,$n);return $n;}
    public function getArticle($id){$key=$this->key('article.'.(int)$id);$c=$this->getCache($key);if($c!==false)return $c;$l=(int)$this->config->get('config_language_id');$r=$this->db->query("SELECT a.*,ad.title,ad.short_description,ad.description,ad.meta_title,ad.meta_description,ad.meta_keyword,cd.title AS category_title FROM `".DB_PREFIX."probg_blog_article` a INNER JOIN `".DB_PREFIX."probg_blog_article_description` ad ON(ad.article_id=a.article_id AND ad.language_id='".$l."') INNER JOIN `".DB_PREFIX."probg_blog_category` c ON(c.category_id=a.category_id AND c.status='1') INNER JOIN `".DB_PREFIX."probg_blog_category_description` cd ON(cd.category_id=a.category_id AND cd.language_id='".$l."') WHERE a.article_id='".(int)$id."' AND a.status='1'")->row;$this->setCache($key,$r);return $r;}
    public function getArticleImages($id){$key=$this->key('images.'.(int)$id);$c=$this->getCache($key);if($c!==false)return $c;$r=$this->db->query("SELECT * FROM `".DB_PREFIX."probg_blog_article_image` WHERE article_id='".(int)$id."' ORDER BY sort_order ASC,article_image_id ASC")->rows;$this->setCache($key,$r);return $r;}
    public function getSitemapData(){ $key=$this->key('sitemap');$c=$this->getCache($key);if($c!==false)return $c;$l=(int)$this->config->get('config_language_id');$cats=$this->db->query("SELECT c.category_id,c.date_modified FROM `".DB_PREFIX."probg_blog_category` c INNER JOIN `".DB_PREFIX."probg_blog_category_description` cd ON(cd.category_id=c.category_id AND cd.language_id='".$l."') WHERE c.status='1'")->rows;$arts=$this->db->query("SELECT a.article_id,a.category_id,a.date_modified FROM `".DB_PREFIX."probg_blog_article` a INNER JOIN `".DB_PREFIX."probg_blog_article_description` ad ON(ad.article_id=a.article_id AND ad.language_id='".$l."') INNER JOIN `".DB_PREFIX."probg_blog_category` c ON(c.category_id=a.category_id AND c.status='1') WHERE a.status='1'")->rows;$r=array('categories'=>$cats,'articles'=>$arts);$this->setCache($key,$r);return $r; }
    private function key($suffix){return 'probg_blog.'.(int)$this->config->get('config_store_id').'.'.(int)$this->config->get('config_language_id').'.'.$suffix;}
    private function getCache($key){if(!$this->config->get('module_probg_blog_cache'))return false;$v=$this->cache->get($key);return $v===null?false:$v;}
    private function setCache($key,$value){if($this->config->get('module_probg_blog_cache'))$this->cache->set($key,$value);}
}
