<?php
$_['heading_title']='ProBG Blog';
$_['text_home']='Начало';$_['text_extension']='Разширения';$_['text_success']='Настройките на ProBG Blog са запазени успешно.';$_['text_edit']='Настройки на ProBG Blog';$_['text_enabled']='Включен';$_['text_disabled']='Изключен';$_['text_stage']='Етап';$_['text_version']='Версия';$_['text_categories']='Категории';$_['text_articles']='Статии';$_['text_settings']='Настройки';$_['text_stage_info']='Версия 1.4.2 показва статиите в режим Списък със същите визуални карти като в режим Слайдър.';
$_['text_general']='Общи';$_['text_content']='Данни';$_['text_menu']='Меню';$_['text_images']='Изображения';$_['text_integrations']='Интеграции и производителност';$_['text_date']='По дата';$_['text_sort_order']='По подредба';$_['text_layout_articles']='Последни статии';$_['text_layout_menu']='Меню';$_['text_all_categories']='Всички категории';
$_['entry_status']='Статус';$_['entry_sort']='Подредба на статии';$_['entry_limit']='Статии на страница';$_['entry_title']='Заглавие на секцията';$_['entry_description']='Описание';$_['entry_meta_title']='Мета заглавие';$_['entry_meta_description']='Мета описание';$_['entry_meta_keyword']='Мета ключови думи';$_['entry_seo_keyword']='SEO URL';$_['entry_default_image']='Изображение по подразбиране';$_['entry_image_list']='Размер в списък';$_['entry_image_article']='Размер на основно изображение';$_['entry_image_gallery']='Размер на галерия';$_['entry_sitemap']='Добавяне в sitemap';$_['entry_cache']='Кеширане';
$_['entry_layout_output']='Изглед в layout';$_['entry_menu_title']='Заглавие на менюто';$_['entry_menu_show_blog']='Покажи линк към блога';$_['entry_menu_show_categories']='Покажи категории';$_['entry_menu_show_articles']='Покажи статии';$_['entry_menu_category']='Категория за статиите';$_['entry_menu_limit']='Брой статии в менюто';$_['entry_menu_sort']='Подредба на статиите в менюто';
$_['help_seo_keyword']='Оставете празно за автоматично генериране от заглавието.';$_['help_layout_output']='Изберете какво да показва текущият ProBG Blog модул, когато е поставен в Design → Layouts. Менюто е част от този модул и не изисква отделна инсталация.';$_['help_menu_category']='Ограничете статиите в менюто до конкретна категория или изберете всички категории.';
$_['button_save']='Запази';$_['button_cancel']='Отказ';$_['button_categories']='Категории';$_['button_articles']='Статии';
$_['error_permission']='Нямате права за промяна на ProBG Blog.';$_['error_title']='Заглавието не може да е по-дълго от 255 символа.';$_['error_menu_title']='Заглавието на менюто не може да е по-дълго от 255 символа.';$_['error_seo_keyword']='SEO URL може да съдържа само латински букви, цифри, тире и долна черта.';$_['error_limit']='Лимитът трябва да бъде между 1 и 100.';$_['error_menu_limit']='Броят статии в менюто трябва да бъде между 1 и 100.';$_['error_image']='Всички размери на изображенията трябва да са положителни числа.';
$_['text_menu_blog']='Блог';$_['text_menu_articles']='Статии';$_['text_menu_categories']='Категории';$_['text_menu_settings']='Настройки';$_['entry_menu_name']='Име на менюто';$_['entry_menu_status']='Статус на менюто';$_['entry_menu_display']='Изглед на статиите';$_['entry_slider_items']='Статии на екран';$_['entry_slider_autoplay']='Автоматично превъртане';$_['entry_slider_interval']='Интервал (ms)';$_['text_menu_list']='Списък';$_['text_menu_slider']='Слайдър';$_['help_multiple_menus']='Създайте неограничен брой менюта. Всяко се записва като отделна OpenCart module instance и може да бъде избрано независимо в Design → Layouts.';$_['help_slider_items']='Брой едновременно видими статии на широк екран. На tablet/mobile броят се адаптира автоматично.';$_['button_add_menu']='Добави меню';$_['button_remove_menu']='Премахни меню';$_['error_menu_name']='Името на менюто е задължително и трябва да е до 64 символа.';$_['error_slider_items']='Броят статии на екран трябва да е между 1 и 6.';$_['error_slider_interval']='Интервалът трябва да е между 1000 и 30000 ms.';
