<?php
class ControllerExtensionModuleProbgBlogArticles extends Controller {
    private $error=array();
    public function index(){
        $this->load->language('extension/module/probg_blog_articles');$this->document->setTitle($this->language->get('heading_title'));$this->load->model('setting/module');$this->load->model('extension/probg_blog/category');
        if(($this->request->server['REQUEST_METHOD']==='POST')&&$this->validate()){
            if(!isset($this->request->get['module_id']))$this->model_setting_module->addModule('probg_blog_articles',$this->request->post);else $this->model_setting_module->editModule($this->request->get['module_id'],$this->request->post);
            $this->session->data['success']=$this->language->get('text_success');$this->response->redirect($this->url->link('marketplace/extension','user_token='.$this->session->data['user_token'].'&type=module',true));
        }
        foreach(array('heading_title','text_edit','text_enabled','text_disabled','text_all_categories','text_global','text_date','text_sort_order','entry_name','entry_title','entry_category','entry_limit','entry_order','entry_show_image','entry_show_date','entry_show_category','entry_status','button_save','button_cancel') as $k)$data[$k]=$this->language->get($k);
        $data['error_warning']=isset($this->error['warning'])?$this->error['warning']:'';$data['error_name']=isset($this->error['name'])?$this->error['name']:'';$data['error_limit']=isset($this->error['limit'])?$this->error['limit']:'';
        $data['breadcrumbs']=array(array('text'=>$this->language->get('text_home'),'href'=>$this->url->link('common/dashboard','user_token='.$this->session->data['user_token'],true)),array('text'=>$this->language->get('text_extension'),'href'=>$this->url->link('marketplace/extension','user_token='.$this->session->data['user_token'].'&type=module',true)),array('text'=>$this->language->get('heading_title'),'href'=>$this->url->link('extension/module/probg_blog_articles','user_token='.$this->session->data['user_token'],true)));
        if(!isset($this->request->get['module_id']))$data['action']=$this->url->link('extension/module/probg_blog_articles','user_token='.$this->session->data['user_token'],true);else $data['action']=$this->url->link('extension/module/probg_blog_articles','user_token='.$this->session->data['user_token'].'&module_id='.(int)$this->request->get['module_id'],true);$data['cancel']=$this->url->link('marketplace/extension','user_token='.$this->session->data['user_token'].'&type=module',true);
        $module_info=array();if(isset($this->request->get['module_id'])&&$this->request->server['REQUEST_METHOD']!=='POST')$module_info=$this->model_setting_module->getModule($this->request->get['module_id']);$get=function($key,$default='')use($module_info){return isset($this->request->post[$key])?$this->request->post[$key]:(isset($module_info[$key])?$module_info[$key]:$default);};
        $data['name']=$get('name');$data['title']=$get('title',array());$data['category_id']=$get('category_id',0);$data['limit']=$get('limit',4);$data['order']=$get('order','global');$data['show_image']=$get('show_image',1);$data['show_date']=$get('show_date',1);$data['show_category']=$get('show_category',1);$data['status']=$get('status',1);$data['categories']=$this->model_extension_probg_blog_category->getCategories(array('sort'=>'cd.title','order'=>'ASC'));
        $this->load->model('localisation/language');$data['languages']=$this->model_localisation_language->getLanguages();$data['header']=$this->load->controller('common/header');$data['column_left']=$this->load->controller('common/column_left');$data['footer']=$this->load->controller('common/footer');$this->response->setOutput($this->load->view('extension/module/probg_blog_articles',$data));
    }
    protected function validate(){if(!$this->user->hasPermission('modify','extension/module/probg_blog_articles'))$this->error['warning']=$this->language->get('error_permission');if(!isset($this->request->post['name'])||utf8_strlen($this->request->post['name'])<3||utf8_strlen($this->request->post['name'])>64)$this->error['name']=$this->language->get('error_name');$limit=isset($this->request->post['limit'])?(int)$this->request->post['limit']:0;if($limit<1||$limit>50)$this->error['limit']=$this->language->get('error_limit');return !$this->error;}
}
