<?php
$_['heading_title']='Категории статии';
$_['text_home']='Начало';$_['text_blog']='ProBG Blog';$_['text_list']='Списък с категории';$_['text_add']='Добавяне на категория';$_['text_edit']='Редакция на категория';$_['text_success']='Категорията е записана успешно.';$_['text_success_delete']='Избраните категории са изтрити успешно.';$_['text_enabled']='Разрешен';$_['text_disabled']='Забранен';$_['text_all']='Всички';$_['text_no_results']='Няма намерени категории.';$_['text_confirm']='Сигурни ли сте?';$_['text_general']='Общи';$_['text_settings']='Настройки';$_['text_automatic']='Генерира се автоматично при запис';$_['text_default']='По подразбиране';$_['text_tab_settings']='Настройки';$_['text_tab_categories']='Категории';$_['text_tab_articles']='Статии';
$_['column_title']='Заглавие';$_['column_sort_order']='Подредба';$_['column_status']='Статус';$_['column_date_added']='Дата на добавяне';$_['column_date_modified']='Дата на обновяване';$_['column_action']='Действие';
$_['entry_title']='Заглавие';$_['entry_description']='Описание';$_['entry_seo_keyword']='SEO URL';$_['entry_tags']='Тагове';$_['entry_meta_title']='Мета заглавие';$_['entry_meta_description']='Мета описание';$_['entry_meta_keyword']='Ключови думи';$_['entry_sort_order']='Подредба';$_['entry_status']='Статус';$_['entry_store']='Магазини';$_['entry_layout']='Layout Override';$_['entry_date_added']='Дата на добавяне';$_['entry_date_modified']='Дата на обновяване';
$_['help_seo_keyword']='Оставете празно, за да се генерира автоматично от Заглавие чрез транслитерация.';$_['help_tags']='Въведете тагове за този език, разделени със запетая.';
$_['button_add']='Добави';$_['button_delete']='Изтрий';$_['button_edit']='Редактирай';$_['button_filter']='Филтър';$_['button_settings']='Настройки';$_['button_save']='Запиши';$_['button_cancel']='Отказ';
$_['error_warning']='Проверете внимателно формата за грешки.';$_['error_permission']='Нямате права за промяна на категориите на блога.';$_['error_title']='Заглавието трябва да бъде между 1 и 255 символа.';$_['error_seo_keyword_exists']='SEO URL е невалиден или вече се използва за избрания език.';$_['error_article']='Категорията не може да бъде изтрита, защото към нея има %s статии.';
$_['date_format_short']='d.m.Y';$_['datetime_format']='d.m.Y H:i';$_['text_pagination']='Показани от %d до %d от общо %d (%d страници)';
