<?php
class ControllerExtensionModuleProbgBlog extends Controller {
    public function index($setting=array()) {
        if(!$this->config->get('module_probg_blog_status'))return '';
        $this->load->language('extension/module/probg_blog');$this->load->model('extension/probg_blog/blog');$this->load->model('tool/image');
        if($setting && !isset($this->request->get['probg_blog_category_id']) && !isset($this->request->get['probg_blog_article_id'])) return $this->module($setting);
        $category_id=isset($this->request->get['probg_blog_category_id'])?(int)$this->request->get['probg_blog_category_id']:0;$article_id=isset($this->request->get['probg_blog_article_id'])?(int)$this->request->get['probg_blog_article_id']:0;
        if($article_id)return $this->article($article_id,$category_id);if($category_id)return $this->category($category_id);return $this->listing();
    }
    private function listing(){
        $page=max(1,isset($this->request->get['page'])?(int)$this->request->get['page']:1);$limit=max(1,(int)$this->config->get('module_probg_blog_limit'));$desc=$this->section();$title=!empty($desc['title'])?$desc['title']:$this->language->get('heading_title');$this->meta($desc,$title);$canonical=$this->url->link('extension/module/probg_blog',$page>1?'page='.$page:'',true);$this->document->addLink($canonical,'canonical');$this->social($title,isset($desc['meta_description'])?$desc['meta_description']:'',$canonical,'website','');
        $data=$this->layoutData();$data['heading_title']=$title;$data['description']=isset($desc['description'])?html_entity_decode($desc['description'],ENT_QUOTES,'UTF-8'):'';$data['text_categories']=$this->language->get('text_categories');$data['text_articles']=$this->language->get('text_articles');$data['text_read_more']=$this->language->get('text_read_more');$data['text_no_results']=$this->language->get('text_no_results');$data['breadcrumbs']=$this->breadcrumbs();$data['categories']=array();foreach($this->model_extension_probg_blog_blog->getCategories() as $c)$data['categories'][]=array('title'=>$c['title'],'description'=>html_entity_decode($c['description'],ENT_QUOTES,'UTF-8'),'article_count'=>$c['article_count'],'href'=>$this->url->link('extension/module/probg_blog','probg_blog_category_id='.(int)$c['category_id'],true));
        $total=$this->model_extension_probg_blog_blog->getTotalArticles();$data['articles']=$this->articleCards($this->model_extension_probg_blog_blog->getArticles(array('start'=>($page-1)*$limit,'limit'=>$limit)));$this->pagination($data,$total,$page,$limit,'');return $this->render('probg_blog_list',$data);
    }
    private function category($id){
        $cat=$this->model_extension_probg_blog_blog->getCategory($id);if(!$cat)return $this->notFound();$page=max(1,isset($this->request->get['page'])?(int)$this->request->get['page']:1);$limit=max(1,(int)$this->config->get('module_probg_blog_limit'));$this->meta($cat,$cat['title']);$canonical=$this->url->link('extension/module/probg_blog','probg_blog_category_id='.$id.($page>1?'&page='.$page:''),true);$this->document->addLink($canonical,'canonical');$this->social($cat['title'],$cat['meta_description'],$canonical,'website','');
        $data=$this->layoutData();$data['heading_title']=$cat['title'];$data['description']=html_entity_decode($cat['description'],ENT_QUOTES,'UTF-8');$data['text_read_more']=$this->language->get('text_read_more');$data['text_no_results']=$this->language->get('text_no_results');$data['breadcrumbs']=$this->breadcrumbs(array(array('text'=>$cat['title'],'href'=>$this->url->link('extension/module/probg_blog','probg_blog_category_id='.$id,true))));$total=$this->model_extension_probg_blog_blog->getTotalArticles($id);$data['articles']=$this->articleCards($this->model_extension_probg_blog_blog->getArticles(array('category_id'=>$id,'start'=>($page-1)*$limit,'limit'=>$limit)));$this->pagination($data,$total,$page,$limit,'probg_blog_category_id='.$id);return $this->render('probg_blog_category',$data);
    }
    private function article($id,$requested_category=0){
        $a=$this->model_extension_probg_blog_blog->getArticle($id);if(!$a)return $this->notFound();$canonical=$this->url->link('extension/module/probg_blog','probg_blog_category_id='.(int)$a['category_id'].'&probg_blog_article_id='.$id,true);if($requested_category && $requested_category!=(int)$a['category_id']){$this->response->redirect($canonical,301);return '';}$this->meta($a,$a['title']);$this->document->addLink($canonical,'canonical');$image=$this->image($a['image'],1200,630);$this->social($a['title'],$a['meta_description'],$canonical,'article',$image,$a);
        $data=$this->layoutData();$data['heading_title']=$a['title'];$data['short_description']=html_entity_decode($a['short_description'],ENT_QUOTES,'UTF-8');$data['description']=html_entity_decode($a['description'],ENT_QUOTES,'UTF-8');$data['image']=$this->image($a['image'],max(1,(int)$this->config->get('module_probg_blog_image_article_width')),max(1,(int)$this->config->get('module_probg_blog_image_article_height')));$data['date_added']=date($this->language->get('date_format_short'),strtotime($a['date_added']));$data['date_modified']=date($this->language->get('date_format_short'),strtotime($a['date_modified']));$data['text_category']=$this->language->get('text_category');$data['text_published']=$this->language->get('text_published');$data['text_modified']=$this->language->get('text_modified');$data['category']=array('title'=>$a['category_title'],'href'=>$this->url->link('extension/module/probg_blog','probg_blog_category_id='.(int)$a['category_id'],true));$data['breadcrumbs']=$this->breadcrumbs(array($data['category'],array('text'=>$a['title'],'href'=>$canonical)));$data['images']=array();foreach($this->model_extension_probg_blog_blog->getArticleImages($id) as $img){if($img['image']&&is_file(DIR_IMAGE.$img['image']))$data['images'][]=array('thumb'=>$this->model_tool_image->resize($img['image'],max(1,(int)$this->config->get('module_probg_blog_image_gallery_width')),max(1,(int)$this->config->get('module_probg_blog_image_gallery_height'))),'popup'=>HTTP_SERVER.'image/'.$img['image']);}return $this->render('probg_blog_article',$data);
    }
    private function module($setting){$data['heading_title']=$this->language->get('heading_title');$data['blog_url']=$this->url->link('extension/module/probg_blog','',true);$data['articles']=$this->articleCards($this->model_extension_probg_blog_blog->getArticles(array('limit'=>4)));return $this->load->view('extension/module/probg_blog',$data);}
    private function articleCards($rows){$out=array();$w=max(1,(int)$this->config->get('module_probg_blog_image_list_width'));$h=max(1,(int)$this->config->get('module_probg_blog_image_list_height'));foreach($rows as $r)$out[]=array('title'=>$r['title'],'short_description'=>html_entity_decode($r['short_description'],ENT_QUOTES,'UTF-8'),'image'=>$this->image($r['image'],$w,$h),'date_added'=>date($this->language->get('date_format_short'),strtotime($r['date_added'])),'category_title'=>$r['category_title'],'category_href'=>$this->url->link('extension/module/probg_blog','probg_blog_category_id='.(int)$r['category_id'],true),'href'=>$this->url->link('extension/module/probg_blog','probg_blog_category_id='.(int)$r['category_id'].'&probg_blog_article_id='.(int)$r['article_id'],true));return $out;}
    private function section(){$all=$this->config->get('module_probg_blog_description');$l=(int)$this->config->get('config_language_id');return is_array($all)&&isset($all[$l])?$all[$l]:array();}
    private function meta($row,$fallback){$title=!empty($row['meta_title'])?$row['meta_title']:$fallback;$this->document->setTitle($title);if(!empty($row['meta_description']))$this->document->setDescription($row['meta_description']);if(!empty($row['meta_keyword']))$this->document->setKeywords($row['meta_keyword']);}
    private function image($path,$w,$h){if(!$path||!is_file(DIR_IMAGE.$path))$path=$this->config->get('module_probg_blog_default_image');return ($path&&is_file(DIR_IMAGE.$path))?$this->model_tool_image->resize($path,$w,$h):'';}
    private function social($title,$description,$url,$type,$image='',$article=array()){$site=$this->config->get('config_name');$meta='<meta property="og:type" content="'.htmlspecialchars($type,ENT_QUOTES,'UTF-8').'" />\n<meta property="og:title" content="'.htmlspecialchars($title,ENT_QUOTES,'UTF-8').'" />\n<meta property="og:description" content="'.htmlspecialchars(strip_tags($description),ENT_QUOTES,'UTF-8').'" />\n<meta property="og:url" content="'.htmlspecialchars($url,ENT_QUOTES,'UTF-8').'" />\n<meta property="og:site_name" content="'.htmlspecialchars($site,ENT_QUOTES,'UTF-8').'" />\n';if($image)$meta.='<meta property="og:image" content="'.htmlspecialchars($image,ENT_QUOTES,'UTF-8').'" />\n';$meta.='<meta name="twitter:card" content="'.($image?'summary_large_image':'summary').'" />\n<meta name="twitter:title" content="'.htmlspecialchars($title,ENT_QUOTES,'UTF-8').'" />\n<meta name="twitter:description" content="'.htmlspecialchars(strip_tags($description),ENT_QUOTES,'UTF-8').'" />\n';if($image)$meta.='<meta name="twitter:image" content="'.htmlspecialchars($image,ENT_QUOTES,'UTF-8').'" />\n';$json=array('@context'=>'https://schema.org','@type'=>$type==='article'?'BlogPosting':'Blog','name'=>$title,'url'=>$url);if($type==='article'){$json['headline']=$title;$json['datePublished']=$article['date_added'];$json['dateModified']=$article['date_modified'];$json['articleSection']=$article['category_title'];if($image)$json['image']=$image;}$meta.='<script type="application/ld+json">'.json_encode($json,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE).'</script>';$this->config->set('probg_blog_social_meta',$meta);}
    private function breadcrumbs($extra=array()){$b=array(array('text'=>$this->language->get('text_home'),'href'=>$this->url->link('common/home','',true)),array('text'=>$this->language->get('heading_title'),'href'=>$this->url->link('extension/module/probg_blog','',true)));foreach($extra as $x)$b[]=$x;return $b;}
    private function layoutData(){return array('column_left'=>$this->load->controller('common/column_left'),'column_right'=>$this->load->controller('common/column_right'),'content_top'=>$this->load->controller('common/content_top'),'content_bottom'=>$this->load->controller('common/content_bottom'));}
    private function pagination(&$data,$total,$page,$limit,$query){$p=new Pagination();$p->total=$total;$p->page=$page;$p->limit=$limit;$p->url=$this->url->link('extension/module/probg_blog',($query?$query.'&':'').'page={page}',true);$data['pagination']=$p->render();$start=$total?(($page-1)*$limit)+1:0;$end=min($total,$page*$limit);$data['results']=sprintf($this->language->get('text_pagination'),$start,$end,$total,ceil($total/$limit));}
    private function render($view,$data){$data['header']=$this->load->controller('common/header');$data['footer']=$this->load->controller('common/footer');return $this->response->setOutput($this->load->view('extension/module/'.$view,$data));}
    private function notFound(){$this->response->addHeader($this->request->server['SERVER_PROTOCOL'].' 404 Not Found');$this->document->setTitle($this->language->get('text_error'));$data=$this->layoutData();$data['heading_title']=$this->language->get('text_error');$data['breadcrumbs']=$this->breadcrumbs();$data['header']=$this->load->controller('common/header');$data['footer']=$this->load->controller('common/footer');$this->response->setOutput($this->load->view('error/not_found',$data));return '';}
}
