<?php
class ControllerExtensionModuleProbgBlogArticles extends Controller {
    public function index($setting) {
        if (!$this->config->get('module_probg_blog_status') || empty($setting['status'])) return '';
        $this->load->language('extension/module/probg_blog_articles');$this->load->model('extension/probg_blog/blog');$this->load->model('tool/image');$language_id=(int)$this->config->get('config_language_id');
        $data['heading_title']=isset($setting['title'][$language_id])&&$setting['title'][$language_id]!==''?$setting['title'][$language_id]:$this->language->get('heading_title');$filter=array('limit'=>max(1,min(50,(int)$setting['limit'])));if(!empty($setting['category_id']))$filter['category_id']=(int)$setting['category_id'];if(isset($setting['order'])&&in_array($setting['order'],array('date','sort_order'),true))$filter['sort']=$setting['order'];
        $data['show_image']=!empty($setting['show_image']);$data['show_date']=!empty($setting['show_date']);$data['show_category']=!empty($setting['show_category']);$data['articles']=array();$w=max(1,(int)$this->config->get('module_probg_blog_image_list_width'));$h=max(1,(int)$this->config->get('module_probg_blog_image_list_height'));
        foreach($this->model_extension_probg_blog_blog->getArticles($filter) as $row){$image=$row['image'];if((!$image||!is_file(DIR_IMAGE.$image))&&$this->config->get('module_probg_blog_default_image'))$image=$this->config->get('module_probg_blog_default_image');$data['articles'][]=array('title'=>$row['title'],'image'=>($data['show_image']&&$image&&is_file(DIR_IMAGE.$image))?$this->model_tool_image->resize($image,$w,$h):'','date_added'=>date($this->language->get('date_format_short'),strtotime($row['date_added'])),'category_title'=>$row['category_title'],'category_href'=>$this->url->link('extension/module/probg_blog','probg_blog_category_id='.(int)$row['category_id'],true),'href'=>$this->url->link('extension/module/probg_blog','probg_blog_category_id='.(int)$row['category_id'].'&probg_blog_article_id='.(int)$row['article_id'],true));}$data['text_read_more']=$this->language->get('text_read_more');return $this->load->view('extension/module/probg_blog_articles',$data);
    }
}
