<?php
$_['heading_title']='ProBG Blog';
$_['text_home']='Home';$_['text_extension']='Extensions';$_['text_success']='ProBG Blog settings saved successfully.';$_['text_edit']='ProBG Blog Settings';$_['text_enabled']='Enabled';$_['text_disabled']='Disabled';$_['text_stage']='Stage';$_['text_version']='Version';$_['text_categories']='Categories';$_['text_articles']='Articles';$_['text_settings']='Settings';$_['text_stage_info']='Version 1.4.2 renders List-mode articles with the same visual cards used by Slider mode.';
$_['text_general']='General';$_['text_content']='Content';$_['text_menu']='Menu';$_['text_images']='Images';$_['text_integrations']='Integrations & Performance';$_['text_date']='By date';$_['text_sort_order']='By sort order';$_['text_layout_articles']='Latest articles';$_['text_layout_menu']='Menu';$_['text_all_categories']='All categories';
$_['entry_status']='Status';$_['entry_sort']='Article sorting';$_['entry_limit']='Articles per page';$_['entry_title']='Section title';$_['entry_description']='Description';$_['entry_meta_title']='Meta Title';$_['entry_meta_description']='Meta Description';$_['entry_meta_keyword']='Meta Keywords';$_['entry_seo_keyword']='SEO URL';$_['entry_default_image']='Default image';$_['entry_image_list']='List image size';$_['entry_image_article']='Main image size';$_['entry_image_gallery']='Gallery image size';$_['entry_sitemap']='Add to sitemap';$_['entry_cache']='Caching';
$_['entry_layout_output']='Layout output';$_['entry_menu_title']='Menu title';$_['entry_menu_show_blog']='Show blog link';$_['entry_menu_show_categories']='Show categories';$_['entry_menu_show_articles']='Show articles';$_['entry_menu_category']='Article category';$_['entry_menu_limit']='Articles in menu';$_['entry_menu_sort']='Menu article sorting';
$_['help_seo_keyword']='Leave empty to generate automatically from the title.';$_['help_layout_output']='Choose what the current ProBG Blog module renders when assigned in Design → Layouts. The menu is part of this module and does not require a separate installation.';$_['help_menu_category']='Limit menu articles to a specific category or use all categories.';
$_['button_save']='Save';$_['button_cancel']='Cancel';$_['button_categories']='Categories';$_['button_articles']='Articles';
$_['error_permission']='You do not have permission to modify ProBG Blog.';$_['error_title']='Title cannot be longer than 255 characters.';$_['error_menu_title']='Menu title cannot be longer than 255 characters.';$_['error_seo_keyword']='SEO URL may contain only Latin letters, numbers, hyphens and underscores.';$_['error_limit']='Limit must be between 1 and 100.';$_['error_menu_limit']='Menu article limit must be between 1 and 100.';$_['error_image']='All image dimensions must be positive numbers.';
$_['text_menu_blog']='Blog';$_['text_menu_articles']='Articles';$_['text_menu_categories']='Categories';$_['text_menu_settings']='Settings';$_['entry_menu_name']='Menu name';$_['entry_menu_status']='Menu status';$_['entry_menu_display']='Article display';$_['entry_slider_items']='Articles per view';$_['entry_slider_autoplay']='Autoplay';$_['entry_slider_interval']='Interval (ms)';$_['text_menu_list']='List';$_['text_menu_slider']='Slider';$_['help_multiple_menus']='Create unlimited menus. Each menu is stored as a separate OpenCart module instance and can be selected independently in Design → Layouts.';$_['help_slider_items']='Number of articles visible on wide screens. Tablet/mobile counts adapt automatically.';$_['button_add_menu']='Add menu';$_['button_remove_menu']='Remove menu';$_['error_menu_name']='Menu name is required and must not exceed 64 characters.';$_['error_slider_items']='Articles per view must be between 1 and 6.';$_['error_slider_interval']='Interval must be between 1000 and 30000 ms.';
