<?php
class ModelExtensionProbgBlogCategory extends Model {
    public function addCategory($data) {
        $this->db->query("INSERT INTO `" . DB_PREFIX . "probg_blog_category` SET `sort_order` = '" . (int)$data['sort_order'] . "', `status` = '" . (int)$data['status'] . "', `date_added` = NOW(), `date_modified` = NOW()");
        $category_id = $this->db->getLastId();
        $this->saveDescriptions($category_id, $data); $this->saveSeoUrls($category_id, $data); $this->clearCache(); return $category_id;
    }
    public function editCategory($category_id, $data) {
        $this->db->query("UPDATE `" . DB_PREFIX . "probg_blog_category` SET `sort_order` = '" . (int)$data['sort_order'] . "', `status` = '" . (int)$data['status'] . "', `date_modified` = NOW() WHERE `category_id` = '" . (int)$category_id . "'");
        $this->saveDescriptions($category_id, $data); $this->saveSeoUrls($category_id, $data); $this->clearCache();
    }
    public function deleteCategory($category_id) {$this->db->query("DELETE FROM `".DB_PREFIX."probg_blog_category` WHERE category_id='".(int)$category_id."'");$this->db->query("DELETE FROM `".DB_PREFIX."probg_blog_category_description` WHERE category_id='".(int)$category_id."'");$this->db->query("DELETE FROM `".DB_PREFIX."seo_url` WHERE query='probg_blog_category_id=".(int)$category_id."'");$this->clearCache();}
    public function getCategory($category_id) {return $this->db->query("SELECT * FROM `".DB_PREFIX."probg_blog_category` WHERE category_id='".(int)$category_id."'")->row;}
    public function getCategoryDescriptions($category_id) {
        $data=array();$q=$this->db->query("SELECT * FROM `".DB_PREFIX."probg_blog_category_description` WHERE category_id='".(int)$category_id."'");foreach($q->rows as $r)$data[$r['language_id']]=array('title'=>$r['title'],'description'=>$r['description'],'meta_title'=>$r['meta_title'],'meta_description'=>$r['meta_description'],'meta_keyword'=>$r['meta_keyword'],'seo_keyword'=>'');
        $q=$this->db->query("SELECT language_id,keyword FROM `".DB_PREFIX."seo_url` WHERE store_id='0' AND query='probg_blog_category_id=".(int)$category_id."'");foreach($q->rows as $r){if(!isset($data[$r['language_id']]))$data[$r['language_id']]=array('title'=>'','description'=>'','meta_title'=>'','meta_description'=>'','meta_keyword'=>'','seo_keyword'=>'');$data[$r['language_id']]['seo_keyword']=$r['keyword'];}return $data;
    }
    public function getCategories($data=array()) {
        $sql="SELECT c.*,cd.title FROM `".DB_PREFIX."probg_blog_category` c LEFT JOIN `".DB_PREFIX."probg_blog_category_description` cd ON(c.category_id=cd.category_id) WHERE cd.language_id='".(int)$this->config->get('config_language_id')."'";if(!empty($data['filter_title']))$sql.=" AND cd.title LIKE '%".$this->db->escape($data['filter_title'])."%'";if(isset($data['filter_status'])&&$data['filter_status']!=='')$sql.=" AND c.status='".(int)$data['filter_status']."'";$sorts=array('cd.title','c.sort_order','c.status','c.date_added','c.date_modified');$sql.=" ORDER BY ".((isset($data['sort'])&&in_array($data['sort'],$sorts,true))?$data['sort']:'c.sort_order').((isset($data['order'])&&$data['order']==='DESC')?' DESC':' ASC').", cd.title ASC";if(isset($data['start'])||isset($data['limit'])){$start=max(0,isset($data['start'])?(int)$data['start']:0);$limit=max(1,isset($data['limit'])?(int)$data['limit']:20);$sql.=" LIMIT ".$start.",".$limit;}return $this->db->query($sql)->rows;
    }
    public function getTotalCategories($data=array()) {$sql="SELECT COUNT(*) AS total FROM `".DB_PREFIX."probg_blog_category` c LEFT JOIN `".DB_PREFIX."probg_blog_category_description` cd ON(c.category_id=cd.category_id) WHERE cd.language_id='".(int)$this->config->get('config_language_id')."'";if(!empty($data['filter_title']))$sql.=" AND cd.title LIKE '%".$this->db->escape($data['filter_title'])."%'";if(isset($data['filter_status'])&&$data['filter_status']!=='')$sql.=" AND c.status='".(int)$data['filter_status']."'";return (int)$this->db->query($sql)->row['total'];}
    public function getTotalArticlesByCategoryId($category_id){return (int)$this->db->query("SELECT COUNT(*) AS total FROM `".DB_PREFIX."probg_blog_article` WHERE category_id='".(int)$category_id."'")->row['total'];}
    public function getSeoUrlByKeyword($keyword,$language_id,$category_id=0){$sql="SELECT * FROM `".DB_PREFIX."seo_url` WHERE store_id='0' AND language_id='".(int)$language_id."' AND keyword='".$this->db->escape($keyword)."'";if($category_id)$sql.=" AND query!='probg_blog_category_id=".(int)$category_id."'";return $this->db->query($sql)->row;}
    private function saveDescriptions($category_id,$data){$this->db->query("DELETE FROM `".DB_PREFIX."probg_blog_category_description` WHERE category_id='".(int)$category_id."'");if(empty($data['category_description'])||!is_array($data['category_description']))return;foreach($data['category_description'] as $language_id=>$v){$title=$this->value($v,'title');$meta=trim($this->value($v,'meta_title'))!==''?$this->value($v,'meta_title'):$title;$this->db->query("INSERT INTO `".DB_PREFIX."probg_blog_category_description` SET category_id='".(int)$category_id."',language_id='".(int)$language_id."',title='".$this->db->escape($title)."',description='".$this->db->escape($this->value($v,'description'))."',meta_title='".$this->db->escape($meta)."',meta_description='".$this->db->escape($this->value($v,'meta_description'))."',meta_keyword='".$this->db->escape($this->value($v,'meta_keyword'))."'");}}
    private function saveSeoUrls($category_id,$data){$this->db->query("DELETE FROM `".DB_PREFIX."seo_url` WHERE query='probg_blog_category_id=".(int)$category_id."'");if(empty($data['category_description'])||!is_array($data['category_description']))return;require_once(DIR_SYSTEM.'library/probg_blog_seo.php');$seo=new ProbgBlogSeo($this->db);$query_key='probg_blog_category_id='.(int)$category_id;foreach($data['category_description'] as $language_id=>$v){$keyword=isset($v['seo_keyword'])?trim($v['seo_keyword']):'';if($keyword==='')$keyword=(int)$category_id.'-'.$seo->slugify($this->value($v,'title'));$keyword=$seo->uniqueKeyword($keyword,$language_id,$query_key);$this->db->query("INSERT INTO `".DB_PREFIX."seo_url` SET store_id='0',language_id='".(int)$language_id."',query='".$this->db->escape($query_key)."',keyword='".$this->db->escape($keyword)."'");}}
    private function clearCache(){ $this->cache->delete('probg_blog'); }
    private function value($d,$k){return isset($d[$k])?$d[$k]:'';}
}
