<?php
$_['heading_title']='Article Categories';
$_['text_home']='Home';$_['text_blog']='ProBG Blog';$_['text_list']='Category List';$_['text_add']='Add Category';$_['text_edit']='Edit Category';$_['text_success']='Blog category saved successfully.';$_['text_success_delete']='Selected categories deleted successfully.';$_['text_enabled']='Enabled';$_['text_disabled']='Disabled';$_['text_all']='All';$_['text_no_results']='No categories found.';$_['text_confirm']='Are you sure?';$_['text_general']='General';$_['text_settings']='Settings';$_['text_automatic']='Generated automatically on save';$_['text_default']='Default';$_['text_tab_settings']='Settings';$_['text_tab_categories']='Categories';$_['text_tab_articles']='Articles';
$_['column_title']='Title';$_['column_sort_order']='Sort Order';$_['column_status']='Status';$_['column_date_added']='Date Added';$_['column_date_modified']='Date Modified';$_['column_action']='Action';
$_['entry_title']='Title';$_['entry_description']='Description';$_['entry_seo_keyword']='SEO URL';$_['entry_tags']='Tags';$_['entry_meta_title']='Meta Title';$_['entry_meta_description']='Meta Description';$_['entry_meta_keyword']='Keywords';$_['entry_sort_order']='Sort Order';$_['entry_status']='Status';$_['entry_store']='Stores';$_['entry_layout']='Layout Override';$_['entry_date_added']='Date Added';$_['entry_date_modified']='Date Modified';
$_['help_seo_keyword']='Leave empty to generate it automatically from the Title using transliteration.';$_['help_tags']='Enter language-specific tags separated by commas.';
$_['button_add']='Add New';$_['button_delete']='Delete';$_['button_edit']='Edit';$_['button_filter']='Filter';$_['button_settings']='Settings';$_['button_save']='Save';$_['button_cancel']='Cancel';
$_['error_warning']='Please check the form carefully for errors.';$_['error_permission']='You do not have permission to modify blog categories.';$_['error_title']='Title must be between 1 and 255 characters.';$_['error_seo_keyword_exists']='SEO URL is invalid or already used for the selected language.';$_['error_article']='This category cannot be deleted because it is assigned to %s articles.';
$_['date_format_short']='d/m/Y';$_['datetime_format']='d/m/Y H:i';$_['text_pagination']='Showing %d to %d of %d (%d Pages)';
